### ISSUE TITLE
Make sabproxy save settings in current directory rather than the home folder 

### ISSUE THREAD

**Issue by masrourmouad** [pgnunes/sabproxy#15]
Make sabproxy save settings in current directory rather than the home folder

**Comment by pgnunes** [comment]
The application runs under the use 'sabproxy' and all settings are saved under the user's home. Any particular reason for the need of any other folder? What do you mean by 'current directory'?

**Comment by masrourmouad** [comment]
current dir is where the jar file is placed
Btw thanks

**Comment by pgnunes** [comment]
There was a bug in the installation script. Fixed on this commit [424e618](https://github.com/pgnunes/sabproxy/commit/424e618bd5c1881f480656395338958c537db51e#diff-130ee2cb3a46ebc1a24087e90116714d).

This was preventing the application from starting under the user 'sabproxy'. The settings are now being saved under /home/sabproxy/.sabproxy. To get this changes on your system you just need to run the installer again (install-sabproxy.sh)

The reason behind this decision is that we want the application to be able to run under different operating systems (including Windows) and without any special privileges (a standard user is able run the application). 

The provided linux script installs the application under /opt (and uses a systemd service) but any user can simply execute the jar and have an instance of sabproxy up and running.

Thanks
PN
